### ISSUE TITLE
Enable Grafana dashboard integration in Kiali

### ISSUE THREAD

**Issue by ca-scribner** [canonical/kiali-k8s-operator#43]
### Enhancement Proposal

Kiali offers [grafana integration](https://kiali.io/docs/configuration/p8s-jaeger-grafana/grafana/), where the Kiali dashboard will include links to more detailed Istio dashboards in Grafana for deep dives into the data.  To enable this integration, Kiali needs:
1. **authenticated** access to Grafana.  Kiali will poll Grafana to check some things (whether the dashboards (see (2)) exist, and possibly grafana's version?).  If Kiali cannot authenticate (or the internal-url doesn't resolve to grafana... or anything else goes wrong) Kiali will not include the Grafana links.  There **may** be a log line in the kiali workload when users refresh a page that should have a grafana link, but sometimes it failed silently too
2. the [Istio dashboards](https://istio.io/latest/docs/ops/integrations/grafana/#option-1-quick-start) to be loaded into Grafana.  If kiali cannot find these, it will not provide links

If this integration is not enabled, Kiali wont add Grafana links into the dashboard.  This includes omitting links for any Tracing dashboards or deep dives, too.

**Comment by ca-scribner** [comment]
I successfully did a POC by manually configuring Kiali and manually loading Istio dashboards into grafana

### Configure Grafana in Kiali
```
juju ssh kiali-k8s/0 --container kiali
# from inside the kiali container, edit `/kiali-configuration/config.yaml` to add grafana.  I don't think there's an editor in here, so I used `cat << EOF > FILENAME ... EOF`.  Could cat, save a local copy, and `juju scp --container kiali kiali-k8s/0:...` it back in
```

In the config, I overrode the `dashboards` field but I dont know if I had to

Example config that worked:
```
auth:
  strategy: anonymous
deployment:
  view_only_mode: true
external_services:
  grafana:
    enabled: true
    auth:
      ca_file: ""
      insecure_skip_verify: false
      password: "hCUAzfXw4reS"
      token: ""
      type: "basic"
      use_kiali_token: false
      username: "admin"
    dashboards:
      - name: "Istio Service Dashboard"
      - name: "Istio Workload Dashboard"
        variables:
          namespace: "var-namespace"
          workload: "var-workload"
    external_url: http://grafana-k8s-0.grafana-k8s-endpoints.kiali.svc.cluster.local:3000
    internal_url: http://grafana-k8s-0.grafana-k8s-endpoints.kiali.svc.cluster.local:3000
  prometheus:
    url: http://prometheus-k8s-0.prometheus-k8s-endpoints.kiali.svc.cluster.local:9090/
istio_namespace: kiali
server:
  port: 20001
  web_root: /
```

Once updating this file you need to reboot the kiali service.  I did that by:
```
juju ssh kiali-k8s/0
# from inside the container
alias pebble=/charm/bin/pebble
export PEBBLE_SOCKET=/charm/containers/$CONTAINER_NAME/pebble.socket
pebble restart kiali
```

### Add the Istio dashboards to Grafana

I **think** the dashboards [already included in istio-k8s](https://github.com/canonical/istio-k8s-operator/tree/main/src/grafana_dashboards) are the ones we need, but I made a quick attempt to use them and although Kiali found them they wouldn't populate with data.  Maybe something about the juju-ification of them broke Kiali's templating?  I did successfully get it to work by taking the dashboards [here](https://istio.io/latest/docs/ops/integrations/grafana/#option-1-quick-start) and manually copying them into grafana (`juju scp --container grafana istio_workload_dashboard.json grafana-k8s/0:/etc/grafana/provisioning/dashboards/istio_workload_dashboard.json`).  As long as I copied the workload dashboard, then the link shown on Kiali's [grafana integration docs](https://kiali.io/docs/configuration/p8s-jaeger-grafana/grafana/) worked.  Probably some others are linked elsewhere?
